; dune file

(executable
  (name plugin)
   (modes plugin)	
   (libraries
      compiler-libs
      compiler-libs.bytecomp 
      compiler-libs.common 
      compiler-libs.optcomp 
      ppx_tools.ast_lifter 
      ppx_tools.metaquot 
      ocaml-compiler-libs.shadow
      ppxlib.astlib
      ppxlib.ast
      ppxlib
      fmt
   )
   (embed_in_plugin_libraries
      compiler-libs
      compiler-libs.bytecomp 
      compiler-libs.common 

      compiler-libs.optcomp 
      ppx_tools.ast_lifter 
      ppx_tools.metaquot 
      ppxlib.ast  
      ppxlib.astlib   
      ocaml-compiler-libs.shadow
      ppxlib.astlib
      ppxlib.ast
      ppxlib
      fmt
))
(install
 (section lib_root)
 (files
  (plugin_introspector.cmxs as introspector/plugins/plugin_introspector.cmxs))
 (package introspector))
